set(_CATKIN_CURRENT_PACKAGE "pepper_meshes")
set(pepper_meshes_VERSION "0.2.4")
set(pepper_meshes_MAINTAINER "Maxime Busy <mbusy@softbankrobotics.com>, Surya Ambrose <surya.ambrose@gmail.com>, Natalia Lyubova <natalia.lyubova@gmail.com>")
set(pepper_meshes_PACKAGE_FORMAT "1")
set(pepper_meshes_BUILD_DEPENDS "java")
set(pepper_meshes_BUILD_EXPORT_DEPENDS )
set(pepper_meshes_BUILDTOOL_DEPENDS "catkin")
set(pepper_meshes_BUILDTOOL_EXPORT_DEPENDS )
set(pepper_meshes_EXEC_DEPENDS )
set(pepper_meshes_RUN_DEPENDS )
set(pepper_meshes_TEST_DEPENDS )
set(pepper_meshes_DOC_DEPENDS )
set(pepper_meshes_URL_WEBSITE "http://github.com/ros-naoqi/pepper_meshes/")
set(pepper_meshes_URL_BUGTRACKER "")
set(pepper_meshes_URL_REPOSITORY "")
set(pepper_meshes_DEPRECATED "")